#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libfm
Version  : 1.3.1
Release  : 1
URL      : https://github.com/lxde/libfm/archive/1.3.1.tar.gz
Source0  : https://github.com/lxde/libfm/archive/1.3.1.tar.gz
Summary  : Library for file management
Group    : Development/Tools
License  : GPL-2.0
Requires: libfm-lib = %{version}-%{release}
Requires: libfm-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : cairo-dev
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk+-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : libxslt-bin
BuildRequires : pango-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : vala

%description
Notes for compilation:
1. This library requires:
- Libtool.
- Intltool 0.40.0 or newer.
- GLib 2.22.0 or newer.
- GTK+ 2.18.0 or newer.
- Libmenu-cache 0.3.2 or newer.

%package dev
Summary: dev components for the libfm package.
Group: Development
Requires: libfm-lib = %{version}-%{release}
Provides: libfm-devel = %{version}-%{release}

%description dev
dev components for the libfm package.


%package lib
Summary: lib components for the libfm package.
Group: Libraries
Requires: libfm-license = %{version}-%{release}

%description lib
lib components for the libfm package.


%package license
Summary: license components for the libfm package.
Group: Default

%description license
license components for the libfm package.


%prep
%setup -q -n libfm-1.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549291913
%autogen --disable-static --with-extra-only
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1549291913
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libfm
cp COPYING %{buildroot}/usr/share/package-licenses/libfm/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libfm
/usr/include/libfm-1.0/fm-extra.h
/usr/include/libfm-1.0/fm-version.h
/usr/include/libfm-1.0/fm-xml-file.h
/usr/lib64/libfm-extra.so
/usr/lib64/pkgconfig/libfm-extra.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfm-extra.so.4
/usr/lib64/libfm-extra.so.4.1.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libfm/COPYING
